{"stackTrace": [["/var/task/main.py", 26, "handler", "for i in iterate_bucket_items(bucket='stripes-clean'):"], ["/var/task/main.py", 20, "iterate_bucket_items", "for page in page_iterator:"], ["/var/runtime/botocore/paginate.py", 255, "__iter__", "response = self._make_request(current_kwargs)"], ["/var/runtime/botocore/paginate.py", 332, "_make_request", "return self._method(**current_kwargs)"], ["/var/runtime/botocore/client.py", 314, "_api_call", "return self._make_api_call(operation_name, kwargs)"], ["/var/runtime/botocore/client.py", 612, "_make_api_call", "raise error_class(parsed_response, operation_name)"]], "errorType": "ClientError", "errorMessage": "An error occurred (AccessDenied) when calling the ListObjectsV2 operation: Access Denied"}